-- ============================================================
-- DEPRECATED — Azure SQL audit tables removed.
--
-- All tables previously here have moved to Unity Catalog (Delta):
--
--   audit.pipeline_audit       -> hpe_catalog.audit.job_log
--   audit.data_quality_log     -> hpe_catalog.audit.data_quality_log
--   audit.pipeline_metadata    -> hpe_catalog.audit.pipeline_config
--   audit.source_extract_meta  -> hpe_catalog.audit.pipeline_config
--
-- DDL for the Unity Catalog tables: data_model/04_audit_schema.sql
--                                   data_model/05_pipeline_config.sql
--
-- ADF no longer needs an Azure SQL linked service for metadata lookups.
-- Config is fetched via the 00_get_metadata Databricks notebook, which
-- queries hpe_catalog.audit.pipeline_config and returns JSON to ADF.
--
-- Watermarks are updated by the 00_update_watermark Databricks notebook
-- (replaces usp_update_extract_watermark stored procedure).
-- ============================================================
